#!/bin/bash

bash $HOME/.config/bspwm/scripts/autostart.sh

pgrep -x sxhkd >/dev/null || sxhkd &

function setopt() {
	bspc config "$1" "$2"
}

function script() {
	sh $HOME/.config/bspwm/scripts/${@} &
	return $?
}

setopt border_width 0
setpt window_gap 8

setopt split_ratio 0.52
setopt focus_follows_pointer true
setopt pointer_follows_focus true
setopt pointer_follows_monitor true

script wallpaper.sh
script monitor.sh
script rules.sh
