import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
padding.x = 10
padding.y = 5
opacity = 0.9

[keyboard]
bindings = [
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
  { key = "Enter", mods = "Alt|Shift", action = "ToggleMaximized" },
]
